---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kbw-productsdisplay-web-config
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_IMAGE_PATH: "https://cdn.keautybeautywarehouse.com/images/"
  API_BASE_URL: http://kbw-productsdisplay-api:3001
