apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dimp
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: dimp-auth-secrets.enc.yaml
  - path: dimp-bot-secrets.enc.yaml
  - path: dimp-server-secrets.enc.yaml
  - path: dimp-auth-env.patch.yaml
  - path: dimp-server-env.patch.yaml
images:
  - name: ghcr.io/1spyral/dimp-auth
    newTag: v2026.02.07.00 # {"$imagepolicy": "flux-system:dimp-auth:tag"}
  - name: ghcr.io/1spyral/dimp-bot
    newTag: v2026.02.07.00 # {"$imagepolicy": "flux-system:dimp-bot:tag"}
  - name: ghcr.io/1spyral/dimp-dashboard
    newTag: v2026.02.07.00 # {"$imagepolicy": "flux-system:dimp-dashboard:tag"}
  - name: ghcr.io/1spyral/dimp-server
    newTag: v2026.02.07.00 # {"$imagepolicy": "flux-system:dimp-server:tag"}
