---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: al-dente

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - backend-configmap.yaml
  - frontend-configmap.yaml
  - secrets.enc.yaml

images:
  - name: ghcr.io/al-dente-ai/al-dente-backend
    newTag: latest
  - name: ghcr.io/al-dente-ai/al-dente-frontend
    newTag: latest
