apiVersion: v1
kind: Service
metadata:
  name: al-dente-backend
  labels:
    app: al-dente
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: al-dente
    tier: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
