apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbw-productsdisplay
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: ghcr-pull-secret.enc.yaml
  - path: configmap.yaml
  - path: secrets.enc.yaml
images:
  - name: ghcr.io/1spyral/kbw-productsdisplay
    newTag: latest
    digest: sha256:3c40b590c9d03693fc040d6187f916302c9670a616686616aafcc8750d35894b # {"$imagepolicy": "flux-system:kbw-productsdisplay:digest"}
