apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbw-productsdisplay
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: ghcr-pull-secret.enc.yaml
  - path: configmap.yaml
  - path: secrets.enc.yaml
images:
  - name: ghcr.io/1spyral/kbw-productsdisplay
    newTag: latest
    digest: sha256:abfa53e9a65a093bdfc190d98ff05f35cb9b528555377102df1c42297f75084c # {"$imagepolicy": "flux-system:kbw-productsdisplay:digest"}
