apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbw-productsdisplay
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: ghcr-pull-secret.enc.yaml
  - path: configmap.yaml
  - path: secrets.enc.yaml
images:
  - name: ghcr.io/1spyral/kbw-productsdisplay
    newTag: latest
    digest: sha256:6b58f56d63b2d5e9396b22f2685104f1d19b3a3531593ddf7828b96b4058db4a # {"$imagepolicy": "flux-system:kbw-productsdisplay:digest"}
