apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbw-productsdisplay
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: ghcr-pull-secret.enc.yaml
  - path: configmap.yaml
  - path: secrets.enc.yaml
images:
  - name: ghcr.io/1spyral/kbw-productsdisplay
    newTag: latest
    digest: sha256:fc234cf1b98b93cf0e8f8f2d4198e2a74fc9faeaf6a488cbc3df605ef684e2d2 # {"$imagepolicy": "flux-system:kbw-productsdisplay:digest"}
  - name: ghcr.io/1spyral/productsdisplay-api
    newTag: latest
    digest: sha256:de64f08185938fff53666b90ba3f2117d7a0ece4b96db7a5aeab888201c9c084 # {"$imagepolicy": "flux-system:kbw-productsdisplay-api:digest"}
