apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbw-productsdisplay
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: ghcr-pull-secret.enc.yaml
  - path: api-configmap.yaml
  - path: api-secrets.enc.yaml
  # - path: web-configmap.yaml
  # - path: web-secrets.enc.yaml
images:
  # - name: ghcr.io/1spyral/kbw-productsdisplay
  #   newTag: latest
  #   digest: sha256:da09034eae8b1a76b5c08b31f1645f443dc9359b1c857246b06fad455822ab16 # {"$imagepolicy": "flux-system:kbw-productsdisplay:digest"}
  - name: ghcr.io/1spyral/productsdisplay-api
    newTag: latest
    digest: sha256:f37d3f6c1e6de2fc0edd5c67fb1dd1b60419c79ce0639e87c4a36487a0b90bb0 # {"$imagepolicy": "flux-system:kbw-productsdisplay-api:digest"}
