apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbw-productsdisplay
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: ghcr-pull-secret.enc.yaml
  - path: configmap.yaml
  - path: secrets.enc.yaml
images:
  - name: ghcr.io/1spyral/kbw-productsdisplay
    newTag: latest
    digest: sha256:90d61f5daa51a8ab26aaf4b424b222812e4d4d1bddc261a97623e04af15b9f62 # {"$imagepolicy": "flux-system:kbw-productsdisplay:digest"}
