apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbw-productsdisplay
resources:
  - ../../base
  - namespace.yaml
patchesStrategicMerge:
  - ghcr-pull-secret.enc.yaml
  - configmap.yaml
  - secrets.enc.yaml
images:
  - name: ghcr.io/1spyral/kbw-productsdisplay
    newTag: latest
    digest: sha256:366d165e8faf380877663bfad0a44cc734aeb99818e46d74f235af7d4c961296 # {"$imagepolicy": "flux-system:kbw-productsdisplay:digest"}
