apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbw-productsdisplay
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: ghcr-pull-secret.enc.yaml
  - path: configmap.yaml
  - path: secrets.enc.yaml
images:
  - name: ghcr.io/1spyral/kbw-productsdisplay
    newTag: latest
    digest: sha256:af75517d8ac762a97e04ec76fd832317409653deeef2e9269146535db0d60e9b # {"$imagepolicy": "flux-system:kbw-productsdisplay:digest"}
