apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbw-productsdisplay
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: ghcr-pull-secret.enc.yaml
  - path: api-secrets.enc.yaml
  - path: web-configmap.yaml
  - path: web-secrets.enc.yaml
images:
  - name: ghcr.io/1spyral/kbw-productsdisplay
    newTag: latest
    digest: sha256:e8720a17df22d7e294cb2379e0a7f40b3766ede31b415ca52aaede3391509c2c # {"$imagepolicy": "flux-system:kbw-productsdisplay:digest"}
  - name: ghcr.io/1spyral/productsdisplay-api
    newTag: latest
    digest: sha256:fc7a65384a346c219230fda73c34d335ca81abead1abf71aa529390c131cc489 # {"$imagepolicy": "flux-system:kbw-productsdisplay-api:digest"}
