apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbw-productsdisplay
resources:
  - ../../base
  - namespace.yaml
patchesStrategicMerge:
  - ghcr-pull-secret.enc.yaml
  - configmap.yaml
  - secrets.enc.yaml
images:
  - name: ghcr.io/1spyral/kbw-productsdisplay
    newTag: latest
    digest: sha256:4bf274ff2b4fb98f7f1b29932f92e292646acd3660f4148799c90cc2550c3d88 # {"$imagepolicy": "flux-system:kbw-productsdisplay:digest"}
