---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-pg

resources:
  - ../../../base

nameSuffix: -shared

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: pg-shared
    path: patch-helmrelease.yaml
