---
apiVersion: v1
kind: Service
metadata:
  name: kbw-productsdisplay-api
spec:
  type: ClusterIP
  selector:
    app: kbw-productsdisplay-api
  ports:
    - name: http
      port: 3001
      targetPort: 3001
