apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sa.yaml
  - rbac-clusterrole.yaml
  - rbac-clusterrolebinding.yaml
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - files:
      - Corefile
    name: coredns
generatorOptions:
  disableNameSuffixHash: true
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: coredns
      k8s-app: kube-dns
