---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - migrate-job.yaml

images:
  - name: ghcr.io/1spyral/dimp-auth-migrate
  - name: ghcr.io/1spyral/dimp-server-migrate
