apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dimp
resources:
  - ../../migrate
images:
  - name: ghcr.io/1spyral/dimp-server-migrate
    newTag: v2026.01.20.00 # {"$imagepolicy": "flux-system:dimp-server-migrate:tag"}
