---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dimp-bot
  labels:
    app: dimp-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dimp-bot
  template:
    metadata:
      labels:
        app: dimp-bot
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: next
          image: ghcr.io/1spyral/dimp-bot
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: NODE_ENV
              value: "production"
          envFrom:
            - configMapRef:
                name: dimp-bot-config
            - secretRef:
                name: dimp-bot-secrets
