---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../infra/cert-manager/
  - ../../infra/coredns/
  - ../../infra/helm-repos/
  - ../../infra/longhorn/
  - ../../infra/traefik/
  - ../../infra/pg/
  # Postgres instances
  # - ../../infra/pg/overlays/shared/instance
