---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../infra/cert-manager/
  - ../../infra/cnpg/
  - ../../infra/coredns/
  - ../../infra/helm-repos/
  - ../../infra/longhorn/
  - ../../infra/traefik/
