apiVersion: v1
kind: Service
metadata:
  name: al-dente-frontend
  labels:
    app: al-dente
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: al-dente
    tier: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
