---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: al-dente
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - al-dente.site
      secretName: al-dente-site-tls
  rules:
    - host: al-dente.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: al-dente-frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: al-dente-backend
                port:
                  number: 3000
